### ISSUE TITLE
Switch to POST if the URI is too long

### ISSUE THREAD

**Issue by ggrossetie** [yuzutech/kroki-go#11]
When using very large Vega specification file (when data is embed in the file), the public instance of Kroki can return the following error "414 Request-URI Too Large nginx/1.14.0 (Ubuntu)".

I think we should use a POST request to avoid this error if the URI is longer than X. Or we could always use POST requests ?

**Comment by ggrossetie** [comment]
I believe that NGINX max URI size is [8Kb](http://nginx.org/en/docs/http/ngx_http_core_module.html#large_client_header_buffers) so 4096 is a safe length. 

> Or we could always use POST requests ?

For now we still use GET requests if the URI length is < 4096 because I believe that corporate proxies are more likely to block POST requests than GET requests.

**Comment by fernan256** [comment]
Hi @Mogztter the POST request for bigger URI size is already implemented and deployed?

**Comment by ggrossetie** [comment]
Hi Diego, yes it's available in the Kroki CLI v0.3.0: https://github.com/yuzutech/kroki-cli/releases/tag/v0.3.0

Please give it a try and let me know if it's working for you.

**Comment by fernan256** [comment]
Awesome, just try it and works perfectly. Thanks!!

**Comment by ggrossetie** [comment]
Perfect 👌
